services:
  db:
    container_name: "myapp_db"
    image: mariadb
    ports:
      - "33306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - "mariadb:/var/lib/mysql"

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: "myapp_phpmyadmin"
    ports:
      - "3001:80"
    environment:
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: ""

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      
volumes:
  mariadb:
    name: "myapp_db"